# Generated by Django 3.0.2 on 2020-06-02 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=11)),
                ('complain_count', models.IntegerField(blank=True, null=True)),
                ('count_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
